### ISSUE TITLE
Cannot load such file

### ISSUE THREAD

**Issue by malex1024** [jarmo/RAutomation#111]
C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rautomation (LoadError)
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from quickbooks.rb:11:in `<main>'

I have no idea why this is happening. I do a simple gem install, and then require the 'rautomation' gem in my code and it breaks. ._.

**Comment by enkessler** [comment]
Are you using Bundler?

**Comment by jarmo** [comment]
Closing this due to inactivity.
